[package]
name = "render_derive"
version = "0.1.0"
edition = "2021"
authors = ["Vladyslav <nylestroke> Potapenko"]

[dependencies]
quote = "1.0.28"
syn = { version = "2.0.18", features = ["parsing"] }
proc-macro2 = "1.0.59"

[lib]
proc-macro = true
